name: Maven Build and Execute Goals

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'
    
    - name: Build Maven project
      run: mvn clean install

    - name: Display Maven Goals Output
      run: |
        mvn help:describe -Dcmd=help
